# Generated by Django 3.2.7 on 2021-09-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='nombres')),
                ('pais', models.CharField(max_length=50, verbose_name='nombres')),
                ('edad', models.IntegerField(verbose_name='edad')),
            ],
            options={
                'verbose_name': 'Inicio',
                'verbose_name_plural': 'Inicios',
                'db_table': 'homes',
            },
        ),
    ]
