# Generated by Django 3.2.7 on 2021-09-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='pais_secundario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nombres'),
        ),
    ]
