# Generated by Django 3.2.7 on 2021-09-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_pais_secundario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='home',
            unique_together={('pais', 'pais_secundario')},
        ),
        migrations.AddConstraint(
            model_name='home',
            constraint=models.CheckConstraint(check=models.Q(('edad__gte', 18)), name='edad_mayor_18'),
        ),
    ]
