# Generated by Django 3.2.7 on 2021-09-26 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210925_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina1',
            fields=[
                ('home_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.home')),
                ('url', models.CharField(max_length=50, verbose_name='url')),
            ],
            bases=('home.home',),
        ),
        migrations.AlterField(
            model_name='home',
            name='pais',
            field=models.CharField(max_length=50, verbose_name='pais'),
        ),
        migrations.AlterField(
            model_name='home',
            name='pais_secundario',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='pais secundario'),
        ),
    ]
