# Generated by Django 3.2.7 on 2021-09-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210925_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50, verbose_name='url')),
                ('navigation', models.BooleanField(default=False)),
                ('cuerpo_pagina', models.CharField(max_length=500, verbose_name='Cuerpo de la pagina')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
