# Generated by Django 3.2.7 on 2021-09-26 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_add_trigram_extension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo', 'fecha_publicacion'], 'verbose_name': 'Libro en el admin', 'verbose_name_plural': 'Libros en el admin'},
        ),
    ]
