# Generated by Django 3.2.7 on 2021-09-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_libro_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='visitas',
            field=models.PositiveIntegerField(default=0, verbose_name='Visitas'),
        ),
    ]
